### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Roger-Hong** [DeComX/pantheon#4]
https://github.com/DeComX/pantheon/blob/27a600cc5ff92b90f1e2ecc82c4e67fe1b600b41/proto/model.proto#L47

Is this field to store the historic Task OPs on this task? Otherwise, it is not needed.

**Comment by dongshu2013** [comment]
yes, and why is it not needed? Because transactions are stored by ethereum framework automatically?

**Comment by dongshu2013** [comment]
We don't need to store the task ops in ethereum but we will need to store it in IPFS to record the history so let's keep it in the proto for now.
